apiVersion: v1
kind: Service
metadata:
  name: {{ include "coffee-journal-app.fullname" . }}
  namespace: {{ include "coffee-journal-app.namespace" . }}
  labels:
    {{- include "coffee-journal-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "coffee-journal-app.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
